### ISSUE TITLE
Custom annotation for service name

### ISSUE THREAD

**Issue by DanTulovsky** [otterize/network-mapper#128]
According to: https://docs.otterize.com/reference/configuration/network-mapper#pod-annotations setting the `intents.otterize.com/service-name` annotation on a pod will set the name of the service.

Please consider allowing this annotation to be set by the users.  We already have such an annotation on our pods and it would be best not to duplicate it.

(As an aside, maybe a label would be better?  Perhaps default to the `app.kubernetest.io/name` label?  As virtually everything should have that set already.)

Thank you

**Comment by orishoshan** [comment]
Hey @DanTulovsky!

We're thinking of adding a helm-chart configuration value named `global.serviceNameOverrideAnnotationName`. It would go in the `global` section because it applies to multiple subcharts: to the intents-operator, network-mapper and credentials-operator. If you don't specify it, you'll get the default value `intents.otterize.com/service-name`.

Regarding use of labels: we preferred use of an annotation because it is not size-limited, unlike labels.
Since we want to keep it backwards-compatible, we prefer not to use `app.kubernetes.io/name` at the moment, as it would alter default behavior for existing users.

**Comment by usarid** [comment]
LGTM - let’s do it. `global.serviceNameOverrideAnnotationName`
