### ISSUE TITLE
Support emitting map as an OpenTelemetry metric

### ISSUE THREAD

**Issue by smithclay** [otterize/network-mapper#140]
Several different monitoring and observability solutions (like [Grafana tempo](https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/)) can natively visualize maps from timeseries data that follows a specific format.

If network mapper emits a OpenTelemetry timeseries with `from` and `to` edges, the connections inferred from network-mapper can be easily visualized and used in external tools for performance, inventory, and observability use-cases.

**Comment by AdaptiveStep** [comment]
im trying to get this service-map into my tracing pipeline. Anyone got any good idea on how to send the servicemap as traces? Can it be converted somehow? I thought service-maps were supposed to be sent via traces?

**Comment by orishoshan** [comment]
The data here doesn't match 1:1 with traces, since they don't represent individual connections or requests, but rather the presence of any connection within a given time period.

See the configuration flags for the Helm chart for enabling this feature: https://docs.otterize.com/reference/network-mapper/helm-chart#opentelemetry-exporter-parameters
The default metric value should work out of the box with OpenTelemetry Grafana Tempo.

**Comment by AdaptiveStep** [comment]
Ok! Thank you for your reply! 

One last question: are the metrics the same as the ones produced by the [ServiceGraphConnector ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/servicegraphconnector/README.md) ?
