### ISSUE TITLE
"Failed to save state" in mapper

### ISSUE THREAD

**Issue by undera** [otterize/network-mapper#63]
Hi
I have a local Kind cluster where I have installed the network-mapper according to README. 
When I'm trying to run `./otterize mapper list` in my CLI, I get no output. I have noticed log messages in mapper pod:
```
{"time":"2023-01-25T13:44:36.68256383Z","id":"","remote_ip":"10.244.0.1","host":"otterize-network-mapper:9090","method":"POST","uri":"/query","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":61569408,"latency_human":"61.569408ms","bytes_in":2004,"bytes_out":41}                                  │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=kube-system owner=coredns ownerKind="apps/v1, Kind=Deployment" pod=coredns-565d847f94-wvmtf                                                                                                                                             │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=default owner=grafana-agent ownerKind="apps/v1, Kind=DaemonSet" pod=grafana-agent-wkcjz                                                                                                                                                 │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=default owner=crossplane ownerKind="apps/v1, Kind=Deployment" pod=crossplane-6fd66789b9-v7tdw                                                                                                                                           │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=kube-system owner=coredns ownerKind="apps/v1, Kind=Deployment" pod=coredns-565d847f94-4zbw5                                                                                                                                             │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=default owner=crossplane-rbac-manager ownerKind="apps/v1, Kind=Deployment" pod=crossplane-rbac-manager-6f4889484b-bxwcq                                                                                                                 │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=komodor owner=k8s-watcher ownerKind="apps/v1, Kind=Deployment" pod=k8s-watcher-6fc58bbffc-zs9fb                                                                                                                                         │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=default owner=crossplane-contrib-provider-aws ownerKind="pkg.crossplane.io/v1, Kind=Provider" pod=crossplane-contrib-provider-aws-92d22091732f-66dc7448bc-mtj8g                                                                         │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=local-path-storage owner=local-path-provisioner ownerKind="apps/v1, Kind=Deployment" pod=local-path-provisioner-684f458cdd-27sh7                                                                                                        │
│ time="2023-01-25T13:44:46Z" level=info msg="pod resolved to owner name" namespace=otterize-system owner=otterize-network-mapper ownerKind="apps/v1, Kind=Deployment" pod=otterize-network-mapper-5856bd77b7-bq5h7                                                                                                         │
│ time="2023-01-25T13:44:46Z" level=warning msg="Failed to save state into the store file" error="an empty namespace may not be set during creation"                                                                                                                                                                        │```

What do I do wrong? How can I see if network-mapper does discover any connections for me?

**Comment by undera** [comment]
Can it be that this condition should be inversed? https://github.com/otterize/network-mapper/blob/main/src/mapper/pkg/resolvers/helpers.go#L43

**Comment by orishoshan** [comment]
Hey @undera, looking into it now :)

**Comment by orishoshan** [comment]
The logs "pod resolved to owner name" show that the network mapper detected traffic from those pods, however the traffic you are seeing was probably external. Was the traffic you were expecting to see outbound to the Internet, or cluster-local? Try setting up pods that communicate locally and see if you are able to get output.

I tested with a simple app on Kind and was able to detect its traffic using the mapper:
```
~ ❯ otterize mapper list                                                                        
client in namespace otterize-tutorial-mapper calls:
  - server in namespace otterize-tutorial-mapper
client2 in namespace otterize-tutorial-mapper calls:
  - server in namespace otterize-tutorial-mapper
```

Try deploying the app from the [quick tutorial](https://docs.otterize.com/quick-tutorials/k8s-network-mapper).

A bit more about the network mapper and what it captures:

The network mapper only outputs traffic that's cluster-local, so you would not see traffic to the Internet. It does actually detect external traffic as well, but the goal is to map traffic within your cluster, so it does not output it.

Here's how it works:
1. It captures DNS traffic and resolves the pod which made the request, as well as resolving which pod(s) the request refers to.
2. It looks at currently open connections and resolves the IP addresses to the pods.

Both of these also see external traffic, and in the case of DNS - it's actually already meaningful since it comes with names. If you are looking to view external traffic, this could be something we could work on together, and is probably pretty easy to do. If you're up for it, give me [a ping on Slack](https://joinslack.otterize.com/).

On the lack of output: that's a bug, but in your case it just means no output. Fixing it now to be clearer.
On "Failed to save state" - absolutely correct, fixing it. However, unrelated - it should work regardless. That error concerns the network mapper's ability to persist previously detected traffic. Thank you!

**Comment by orishoshan** [comment]
The save state bug was fixed in #65, however this is actually unrelated to your problem where you saw no traffic - re-opening.

**Comment by undera** [comment]
Good morning,
After your explanation I installed the demo app from tutorial and now I see some results. I was just confused by the fact that I expect to see _anything_ because my cluster has network activity. No I understand that it will only show the communications inside the cluster. The error message is unrelated, indeed.

**Comment by undera** [comment]
Thank you for your clarification
